all: student2A.c student2B.c student2_common.c student2_common.h project2.h  project2.c crc32.h crc32.c
	gcc -g -O0 project2.c student2_common.c student2A.c student2B.c crc32.c -o project2

clean:
	rm project2
